### PR TITLE
[#22] Update `settings.py` config example

### PR DESCRIPTION
**Pull request by lenards**
Per [issue 56](https://github.com/owais/django-webpack-loader/issues/56) and [issue 22](https://github.com/owais/django-webpack-loader/issues/22), this _attempts_ to update the `settings.py` example such that it is inline with the [README.md](https://github.com/owais/django-webpack-loader#default-configuration). 

I did the HTML edits & additions by hand (I'd do the React updates to get inline with 0.14 / 15.0 if I knew what tool, or how, the code example were produced - I imagine the HTML is the output from fancybox or something). 

I hope this helps.

### CODE REVIEW

**Comment by owais** [comment]
Thank you @lenards

**Comment by lenards** [comment]
@owais - if I had more information on how the codeblocks were generated, I think I can maybe help with documenting that for future contributions.

**Comment by owais** [comment]
I've not published that part anywhere publicly yet. I'll try to do it in the next few days/weeks.

**Comment by lenards** [comment]
No rush, I just wanted to assist if I can. Thanks again for putting together the module and for trying to modernize the Django static asset tool-chain.

**Pull request merged**
